/**
 * Domain enumerations persisted as VARCHAR. Validated in services, not as Sequelize ENUM,
 * so SQLite and PostgreSQL stay interchangeable.
 */

export const DocumentCategory = {
  PAYSLIP: 'PAYSLIP',
  TAX_PROOF: 'TAX_PROOF',
  REIMBURSEMENT_PROOF: 'REIMBURSEMENT_PROOF',
  PREVIOUS_EMPLOYER: 'PREVIOUS_EMPLOYER',
  DECLARATION: 'DECLARATION',
  OTHER: 'OTHER'
};

export const DocumentStatus = {
  UPLOADED: 'UPLOADED',
  OCR_PENDING: 'OCR_PENDING',
  OCR_COMPLETE: 'OCR_COMPLETE',
  OCR_FAILED: 'OCR_FAILED',
  ARCHIVED: 'ARCHIVED'
};

export const LinkedEntityType = {
  DEDUCTION: 'DEDUCTION',
  REIMBURSEMENT: 'REIMBURSEMENT',
  USER_PROFILE: 'USER_PROFILE',
  PAYROLL_CYCLE: 'PAYROLL_CYCLE'
};

export const EmploymentStatus = {
  ACTIVE: 'ACTIVE',
  PROBATION: 'PROBATION',
  NOTICE_PERIOD: 'NOTICE_PERIOD',
  ON_LEAVE: 'ON_LEAVE',
  EXITED: 'EXITED'
};

export const EmployeeType = {
  FULL_TIME: 'FULL_TIME',
  CONTRACT: 'CONTRACT',
  INTERN: 'INTERN'
};

export const TaxRegime = {
  OLD: 'OLD',
  NEW: 'NEW'
};

export const DeductionScope = {
  PAYROLL: 'PAYROLL',
  TAX_DECLARATION: 'TAX_DECLARATION',
  EMPLOYER: 'EMPLOYER'
};

export const DeductionStatus = {
  DECLARED: 'DECLARED',
  APPLIED: 'APPLIED',
  PROOF_SUBMITTED: 'PROOF_SUBMITTED',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED'
};

export const ReimbursementStatus = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED'
};

export const DeductionSource = {
  EMPLOYEE: 'EMPLOYEE',
  PAYROLL_IMPORT: 'PAYROLL_IMPORT',
  HR: 'HR',
  SYSTEM: 'SYSTEM'
};

export const QueryIntent = {
  SALARY_EXPLAIN: 'SALARY_EXPLAIN',
  COMPONENT_LOOKUP: 'COMPONENT_LOOKUP',
  DEDUCTION_BREAKDOWN: 'DEDUCTION_BREAKDOWN',
  YTD_SUMMARY: 'YTD_SUMMARY',
  TAX_SIMULATION: 'TAX_SIMULATION',
  COMPONENT_EDUCATION: 'COMPONENT_EDUCATION',
  PROOF_CHECKLIST: 'PROOF_CHECKLIST',
  ELIGIBILITY_OPTIONS: 'ELIGIBILITY_OPTIONS',
  DOCUMENT_GROUNDED: 'DOCUMENT_GROUNDED'
};
