export const QueryIntent = {
  SALARY_EXPLAIN: 'SALARY_EXPLAIN',
  DEDUCTION_BREAKDOWN: 'DEDUCTION_BREAKDOWN',
  TAX_SIMULATION: 'TAX_SIMULATION',
  PROOF_CHECKLIST: 'PROOF_CHECKLIST',
  DOCUMENT_GROUNDED: 'DOCUMENT_GROUNDED'
};